# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'NUSJio'

target 'NUSJio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NUSJio

  target 'NUSJioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NUSJioUITests' do
    # Pods for testing
  end

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  pod 'MessageKit'

  pod "AlignedCollectionViewFlowLayout"
  pod "InitialsImageView"
end
